### ISSUE TITLE
pui-react-tools doesn't seem to contain the update including vinyl

### ISSUE THREAD

**Issue by Marlena** [pivotal-cf/react-starter#1]
This is quite a useful project. 

Currently, if you download, install and run as is (git close + npm install + gulp) the build shows an error for a missing vinyl dependency in the pui-react-tools module.  It looks like there is a commit in that repo to include vinyl, but the change doesn't seem to have made it's way into the npm install for this project.

Stacktrace:
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'vinyl'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/marlena/Github/react-starter/node_modules/pui-react-tools/assets/assets.js:10:12)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/marlena/Github/react-starter/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/marlena/Github/react-starter/node_modules/pui-react-tools/index.js:4:11)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/marlena/Github/react-starter/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
```

**Comment by charleshansen** [comment]
I thought the most recent version of pui-react-tools (0.0.5) has fixed this, will look into it. We should be updating it shortly regardless.

In the short term, you can add vinyl yourself `npm install vinyl --save-dev`

The project is still a work in progress, suggestions are very welcome.

**Comment by charleshansen** [comment]
should be fixed now
